codecov:
  require_ci_to_pass: yes
  branch: main
  max_report_age: "12h" # equates to 12 hours
  # max_report_age can be listed in hours '#h' (hours) or '#d' (days)

coverage:
  precision: 2
  round: down
  range: "70...100"

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: no
  require_base: no
  require_head: yes
  show_carryforward_flags: false

ignore:
  - "node_modules"
  - "coverage"
  - "dist"
  - ".next"
  - "out"

flags:
  api:
    carryforward: true
    paths:
      - src/apps/api/src
      - src/apps/api/tests
  web:
    carryforward: true
    paths:
      - src/apps/web/components
      - src/apps/web/pages
      - src/apps/web/hooks
