services:
  api:
    volumes:
      - ./:/app
      - ./src/apps/api:/app/src/apps/api
    command: sh -c "cd /app && HUSKY=0 pnpm install && pnpm --filter infamous-freight-api dev"

  web:
    volumes:
      - ./:/app
      - ./src/apps/web:/app/src/apps/web
    command: sh -c "cd /app && HUSKY=0 pnpm install && pnpm --filter infamous-freight-web dev"
